# Creating a Matrix

We have learned about vectors which allow us to store indexed elements into a one dimensional array. A matrix will allow us to store data into a 2 dimensional data structure which contains the same data types

Before we start, a quick tip to create sequencial numbers is to use colon notation

In [1]:
v <- 1:10 # this will produce a vector of values between 1 and 10
v

[1]  1  2  3  4  5  6  7  8  9 10

Pretty cool! Now lets make a matrix. Use the matrix() function and pass in the vector

In [4]:
(matrix(v)) # this will produce a matrix with 10 rows and 1 column

[,1]
 [1,]  1  
 [2,]  2  
 [3,]  3  
 [4,]  4  
 [5,]  5  
 [6,]  6  
 [7,]  7  
 [8,]  8  
 [9,]  9  
[10,] 10

Notice how the output is displayed. We have created a matrix with 10 rows and 1 column. Maybe we wanted two rows though. using the nrow funciton will define the number of rows we want.

In [5]:
matrix(v,nrow = 2) # nrow forces the matrix to be limited to two rows

[,1] [,2] [,3] [,4] [,5]
[1,] 1    3    5    7     9  
[2,] 2    4    6    8    10

Now we have a 2 x 5 matrix. But maybe we wanted the top row to contain the numbers 1-5. We can use the byrow function to force the matrix to fill in horizontally instead of vertically. 

In [6]:
matrix(1:12,byrow = FALSE, nrow = 4) #byrow = FALSE makes the numbers travel down the column first

[,1] [,2] [,3]
[1,] 1    5     9  
[2,] 2    6    10  
[3,] 3    7    11  
[4,] 4    8    12

In [7]:
matrix(1:12,byrow = TRUE, nrow = 4) #byrow = TRUE makes the numbers travel down the row first

[,1] [,2] [,3]
[1,]  1    2    3  
[2,]  4    5    6  
[3,]  7    8    9  
[4,] 10   11   12

# Creating Matrices from Vectors

We can combine vectors to later input them into a matrix. Create two vectors for the stock prices of Google and Microsoft

stock.goog <- c(450,451,452,445,468) # Let's make some stock prices for Google and Microsoft
stock.msft <- c(230,231,232,233,243)

In [9]:
stocks <- c (stock.goog,stock.msft)
stocks 

[1] 450 451 452 445 468 230 231 232 233 243

In [10]:
stock.matrix <- matrix(stocks,byrow=TRUE,nrow=2)
stock.matrix

[,1] [,2] [,3] [,4] [,5]
[1,] 450  451  452  445  468 
[2,] 230  231  232  233  243

# Naming Matrices

Now that we've created our matrix, it would be wise to name the columns and rows for reference. We can do this similarly to the names() function for vectors, but in this case, we will define colnames() and nownames().

In [13]:
days <- c("Mon","Tues","Wed","Thur","Fri") #lets add names to the rows and columns of the matrix
stock.names <- c("GOOG","MSFT")
colnames(stock.matrix) <- days
rownames(stock.matrix) <- stock.names
stock.matrix

Mon Tues Wed Thur Fri
GOOG 450 451  452 445  468
MSFT 230 231  232 233  243

Looking good! We are making progress! 

That's it for the introduction to matrices. 