# Matrix Arithmetic

We can perform element by element mathematical operations on a matrix with a scalar number like we would with a vector. Let's try it out

In [8]:
mat <- matrix(1:50,byrow=TRUE,nrow=5)
mat

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10]
[1,]  1    2    3    4    5    6    7    8    9   10   
[2,] 11   12   13   14   15   16   17   18   19   20   
[3,] 21   22   23   24   25   26   27   28   29   30   
[4,] 31   32   33   34   35   36   37   38   39   40   
[5,] 41   42   43   44   45   46   47   48   49   50

In [12]:
mat * 10 # Multiplication

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10]
[1,]  10   20   30   40   50   60   70   80   90  100  
[2,] 110  120  130  140  150  160  170  180  190  200  
[3,] 210  220  230  240  250  260  270  280  290  300  
[4,] 310  320  330  340  350  360  370  380  390  400  
[5,] 410  420  430  440  450  460  470  480  490  500

In [11]:
mat / 10 # Division

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10]
[1,] 0.1  0.2  0.3  0.4  0.5  0.6  0.7  0.8  0.9  1    
[2,] 1.1  1.2  1.3  1.4  1.5  1.6  1.7  1.8  1.9  2    
[3,] 2.1  2.2  2.3  2.4  2.5  2.6  2.7  2.8  2.9  3    
[4,] 3.1  3.2  3.3  3.4  3.5  3.6  3.7  3.8  3.9  4    
[5,] 4.1  4.2  4.3  4.4  4.5  4.6  4.7  4.8  4.9  5

In [13]:
mat ^ 2 # Power

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10]
[1,]    1    4    9   16   25   36   49   64   81  100 
[2,]  121  144  169  196  225  256  289  324  361  400 
[3,]  441  484  529  576  625  676  729  784  841  900 
[4,]  961 1024 1089 1156 1225 1296 1369 1444 1521 1600 
[5,] 1681 1764 1849 1936 2025 2116 2209 2304 2401 2500

## Comparison Operators with Matrices

We can similarly perform comparison operations across an entire matrix to return a matrix of boolean values

In [14]:
mat > 13 # returns boolean values for each element

[,1]  [,2]  [,3]  [,4]  [,5]  [,6]  [,7]  [,8]  [,9]  [,10]
[1,] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
[2,] FALSE FALSE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE
[3,]  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE
[4,]  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE
[5,]  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE

In [16]:
mat[mat>15] # we can also call the values for the matrix the same way

[1] 21 31 41 22 32 42 23 33 43 24 34 44 25 35 45 16 26 36 46 17 27 37 47 18 28
[26] 38 48 19 29 39 49 20 30 40 50

## Matrix Arithmatic with Multiple Matrices

We can use multiple matrices with arithmatic as well. Each element will find it's corresponding element in the second element

In [18]:
mat + mat # Addition

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10]
[1,]  2    4    6    8   10   12   14   16   18    20  
[2,] 22   24   26   28   30   32   34   36   38    40  
[3,] 42   44   46   48   50   52   54   56   58    60  
[4,] 62   64   66   68   70   72   74   76   78    80  
[5,] 82   84   86   88   90   92   94   96   98   100

In [19]:
mat / mat #D ivision

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10]
[1,] 1    1    1    1    1    1    1    1    1    1    
[2,] 1    1    1    1    1    1    1    1    1    1    
[3,] 1    1    1    1    1    1    1    1    1    1    
[4,] 1    1    1    1    1    1    1    1    1    1    
[5,] 1    1    1    1    1    1    1    1    1    1

In [21]:
mat ^ mat # Power (big numbers)

[,1]         [,2]         [,3]         [,4]         [,5]        
[1,] 1.000000e+00 4.000000e+00 2.700000e+01 2.560000e+02 3.125000e+03
[2,] 2.853117e+11 8.916100e+12 3.028751e+14 1.111201e+16 4.378939e+17
[3,] 5.842587e+27 3.414279e+29 2.088047e+31 1.333736e+33 8.881784e+34
[4,] 1.706917e+46 1.461502e+48 1.291100e+50 1.175664e+52 1.102507e+54
[5,] 1.330878e+66 1.501309e+68 1.734377e+70 2.050774e+72 2.480636e+74
     [,6]         [,7]         [,8]         [,9]         [,10]       
[1,] 4.665600e+04 8.235430e+05 1.677722e+07 3.874205e+08 1.000000e+10
[2,] 1.844674e+19 8.272403e+20 3.934641e+22 1.978420e+24 1.048576e+26
[3,] 6.156120e+36 4.434265e+38 3.314552e+40 2.567686e+42 2.058911e+44
[4,] 1.063874e+56 1.055513e+58 1.075912e+60 1.125951e+62 1.208926e+64
[5,] 3.068035e+76 3.877924e+78 5.007021e+80 6.600972e+82 8.881784e+84

In [25]:
mat * mat # Multiplication (or is it...)

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10]
[1,]    1    4    9   16   25   36   49   64   81  100 
[2,]  121  144  169  196  225  256  289  324  361  400 
[3,]  441  484  529  576  625  676  729  784  841  900 
[4,]  961 1024 1089 1156 1225 1296 1369 1444 1521 1600 
[5,] 1681 1764 1849 1936 2025 2116 2209 2304 2401 2500

# Matrix Multiplication
A quick side note on matrix multiplication. You can perform arithmatic mulitplication on an element by element basis by using the * sign in R. 

This is not the same as matrix multiplication though! You should be familiar with the mathematics behind this topic before diving too deep into R. We use dot product for real matrix multiplication. Dot product is calculated by using the characters %*%

In [28]:
mat2 <- matrix(1:9, nrow = 3)
mat3 <- matrix(1:9, nrow = 3, byrow = TRUE)
mat2
mat3

mat2 %*% mat3 # this denotes true matrix multiplcation: the dot product of the matrices

[,1] [,2] [,3]
[1,] 1    4    7   
[2,] 2    5    8   
[3,] 3    6    9

[,1] [,2] [,3]
[1,] 1    2    3   
[2,] 4    5    6   
[3,] 7    8    9

[,1] [,2] [,3]
[1,] 66    78   90 
[2,] 78    93  108 
[3,] 90   108  126

That's enough for matrices. 