In [28]:
mat <- matrix(1:25,byrow=TRUE,nrow=5)
mat

[,1] [,2] [,3] [,4] [,5]
[1,]  1    2    3    4    5  
[2,]  6    7    8    9   10  
[3,] 11   12   13   14   15  
[4,] 16   17   18   19   20  
[5,] 21   22   23   24   25

In [3]:
mat * 10 # you can multiply a matrix by any number (scalar) and all the values will be transformed

[,1] [,2] [,3] [,4] [,5]
[1,]  10   20   30   40   50 
[2,]  60   70   80   90  100 
[3,] 110  120  130  140  150 
[4,] 160  170  180  190  200 
[5,] 210  220  230  240  250

In [4]:
mat / 10 # same principle for division

[,1] [,2] [,3] [,4] [,5]
[1,] 0.1  0.2  0.3  0.4  0.5 
[2,] 0.6  0.7  0.8  0.9  1.0 
[3,] 1.1  1.2  1.3  1.4  1.5 
[4,] 1.6  1.7  1.8  1.9  2.0 
[5,] 2.1  2.2  2.3  2.4  2.5

In [6]:
round(1/mat,2) #taking the inverse of the elements inside the matrix

[,1] [,2] [,3] [,4] [,5]
[1,] 1.00 0.50 0.33 0.25 0.20
[2,] 0.17 0.14 0.12 0.11 0.10
[3,] 0.09 0.08 0.08 0.07 0.07
[4,] 0.06 0.06 0.06 0.05 0.05
[5,] 0.05 0.05 0.04 0.04 0.04

In [30]:
mat > 13# this will check the values within the matrix and return TRUE for the values above 15

[,1]  [,2]  [,3]  [,4]  [,5] 
[1,] FALSE FALSE FALSE FALSE FALSE
[2,] FALSE FALSE FALSE FALSE FALSE
[3,] FALSE FALSE FALSE  TRUE  TRUE
[4,]  TRUE  TRUE  TRUE  TRUE  TRUE
[5,]  TRUE  TRUE  TRUE  TRUE  TRUE

In [33]:
mat[mat>15] 

[1] 16 21 17 22 18 23 19 24 20 25

In [11]:
mat + mat # you can add matrices together. It will take the corresponding indices and add the two together 

[,1] [,2] [,3] [,4] [,5]
[1,]  2    4    6    8   10  
[2,] 12   14   16   18   20  
[3,] 22   24   26   28   30  
[4,] 32   34   36   38   40  
[5,] 42   44   46   48   50

In [29]:
mat * mat #same for multiplication 

[,1] [,2] [,3] [,4] [,5]
[1,]   1    4    9   16   25 
[2,]  36   49   64   81  100 
[3,] 121  144  169  196  225 
[4,] 256  289  324  361  400 
[5,] 441  484  529  576  625

In [37]:
mat * (1/mat)

[,1] [,2] [,3] [,4] [,5]
[1,] 1    1    1    1    1   
[2,] 1    1    1    1    1   
[3,] 1    1    1    1    1   
[4,] 1    1    1    1    1   
[5,] 1    1    1    1    1

# This isn't true matrix multiplication though!

In [34]:
mat %*% mat # this denotes true matrix multiplcation: the dot product of the matrices

[,1] [,2] [,3] [,4] [,5]
[1,]  215  230  245  260  275
[2,]  490  530  570  610  650
[3,]  765  830  895  960 1025
[4,] 1040 1130 1220 1310 1400
[5,] 1315 1430 1545 1660 1775