# Matrix Selection and Indexing

Just like with vectors, we can use the square bracket notation to select an element from a matrix. Since we have two dimensions to work with, we will use a comma to seperate our indexing for each dimension.

The syntax will be:

example.matrix[rows,columns]

where the index notation is put in place of the rows or columns. If either rows or columns is left blank, R will return the whole matrix

Let's try an example

In [2]:
mat <- matrix(1:50,byrow=TRUE,nrow=5)
mat

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10]
[1,]  1    2    3    4    5    6    7    8    9   10   
[2,] 11   12   13   14   15   16   17   18   19   20   
[3,] 21   22   23   24   25   26   27   28   29   30   
[4,] 31   32   33   34   35   36   37   38   39   40   
[5,] 41   42   43   44   45   46   47   48   49   50

In [3]:
#### mat[rows,columns]
mat[1, ] #### If you want the first row

[1]  1  2  3  4  5  6  7  8  9 10

In [4]:
mat[ ,1] #### if you want the first column

[1]  1 11 21 31 41

In [5]:
mat[5,2] #### if you want the 5th row, 2nd column

[1] 42

In [8]:
mat[1:3,2:3] ### get rows 1,2,3 and columns 2, 3

[,1] [,2]
[1,]  2    3  
[2,] 12   13  
[3,] 22   23

In [7]:
# Grab last two columns
mat[,9:10]

[,1] [,2]
[1,]  9   10  
[2,] 19   20  
[3,] 29   30  
[4,] 39   40  
[5,] 49   50

In [9]:
# Grab a center square of:
# 15,16
# 25,26
mat[2:3,5:6]

[,1] [,2]
[1,] 15   16  
[2,] 25   26

Good job!