In [2]:
#### Create 2 vectors A and B, where A is (1,2,3) and B is (4,5,6). With these vectors, use the cbind() and 
#### rbind() function to create a 2 by 3 matrix from the vectors. You'll need to figure out which of these binding functions
#### are the correct choice

In [31]:
A <- c(1:3)
B <- c(4:6)
rbind(A,B)

[,1] [,2] [,3]
A 1    2    3   
B 4    5    6

In [7]:
#### Create a 3 x 3 matrix consisting of the numbers 1-9. Create this matrix using the short cut 1:9 and by specifying the nrow
#### argument in the matrix() function call. Assign this matrix to the variable 'mat'
#### confirm that you created a matrix using the is.matrix() function call

In [16]:
mat <- matrix(1:9,byrow=TRUE,nrow=3)
mat
is.matrix(mat)

[,1] [,2] [,3]
[1,] 1    2    3   
[2,] 4    5    6   
[3,] 7    8    9

[1] TRUE

In [17]:
#### create a 5 x 5 matrix consisting of the numbers 1-25 and assign it to the variable 'mat2'. The top row should be 1-5

In [19]:
mat2 <- matrix(1:25,byrow=T,nrow=5)
mat2

[,1] [,2] [,3] [,4] [,5]
[1,]  1    2    3    4    5  
[2,]  6    7    8    9   10  
[3,] 11   12   13   14   15  
[4,] 16   17   18   19   20  
[5,] 21   22   23   24   25

In [20]:
#### using the index notation, grab a sub-section of mat2 from that looks like this:

####[7,8]
####[12,13]

In [21]:
mat2[2:3,2:3]

[,1] [,2]
[1,]  7    8  
[2,] 12   13

In [22]:
#### what is the sum of all the elements in mat2?

In [26]:
sum(mat2)

[1] 325

In [34]:
#### Last question! Find out how to use runif() to creat a 4 x 5 matrix consisting of 20 random numbers (4*5=20)

In [35]:
help(runif)
####runif(n, min = 0, max = 1)

In [43]:
rand.matrix = matrix(
    runif(20, 
            min = 0,
            max = 100),
    nrow = 4)
rand.matrix

[,1]      [,2]      [,3]      [,4]     [,5]    
[1,] 37.783256  5.301805 85.653999 56.41505 85.03814
[2,] 26.070640  3.561568 22.586446 10.15169 44.64612
[3,]  2.807882 77.954255 36.201598 14.96662 79.78057
[4,] 10.296233 31.669276  3.604267 48.83343 71.06970