In [8]:
v <- c(1,2,3)
m <- matrix(1:10,nrow=2)
df <- head(mtcars,3)
class(v)
class(m)
class(df)

[1] "numeric"

[1] "matrix"

[1] "data.frame"

In [3]:
# lists allow us to add all sorts of data structures into a single variable

In [12]:
my.list <- list(v,m,df)
print(my.list)

[[1]]
[1] 1 2 3

[[2]]
     [,1] [,2] [,3] [,4] [,5]
[1,]    1    3    5    7    9
[2,]    2    4    6    8   10

[[3]]
               mpg cyl disp  hp drat    wt  qsec vs am gear carb
Mazda RX4     21.0   6  160 110 3.90 2.620 16.46  0  1    4    4
Mazda RX4 Wag 21.0   6  160 110 3.90 2.875 17.02  0  1    4    4
Datsun 710    22.8   4  108  93 3.85 2.320 18.61  1  1    4    1



In [21]:
my.named.list <- list(sample.vec =v,sample.matrix = m, sample.df = df)

In [22]:
print(my.named.list)

$sample.vec
[1] 1 2 3

$sample.matrix
     [,1] [,2] [,3] [,4] [,5]
[1,]    1    3    5    7    9
[2,]    2    4    6    8   10

$sample.df
               mpg cyl disp  hp drat    wt  qsec vs am gear carb
Mazda RX4     21.0   6  160 110 3.90 2.620 16.46  0  1    4    4
Mazda RX4 Wag 21.0   6  160 110 3.90 2.875 17.02  0  1    4    4
Datsun 710    22.8   4  108  93 3.85 2.320 18.61  1  1    4    1



In [23]:
my.list[1]
my.named.list['sample.vec']

[[1]]
[1] 1 2 3

$sample.vec
[1] 1 2 3

In [25]:
class(my.named.list)

[1] "list"

In [26]:
double.list <- c(my.named.list, my.named.list)

In [27]:
double.list

$sample.vec
[1] 1 2 3

$sample.matrix
     [,1] [,2] [,3] [,4] [,5]
[1,]    1    3    5    7    9
[2,]    2    4    6    8   10

$sample.df
               mpg cyl disp  hp drat    wt  qsec vs am gear carb
Mazda RX4     21.0   6  160 110 3.90 2.620 16.46  0  1    4    4
Mazda RX4 Wag 21.0   6  160 110 3.90 2.875 17.02  0  1    4    4
Datsun 710    22.8   4  108  93 3.85 2.320 18.61  1  1    4    1

$sample.vec
[1] 1 2 3

$sample.matrix
     [,1] [,2] [,3] [,4] [,5]
[1,]    1    3    5    7    9
[2,]    2    4    6    8   10

$sample.df
               mpg cyl disp  hp drat    wt  qsec vs am gear carb
Mazda RX4     21.0   6  160 110 3.90 2.620 16.46  0  1    4    4
Mazda RX4 Wag 21.0   6  160 110 3.90 2.875 17.02  0  1    4    4
Datsun 710    22.8   4  108  93 3.85 2.320 18.61  1  1    4    1