# R List Basics
We've covered vectors, matrices, and data frames, now we learn abou the last data structure, the list.

Lists allow us to store a variety of data structures under a single variable. This means that we could store a vector, matrix, or data frame under a single list.

Here's an example

In [1]:
# Create a vector
v <- c(1,2,3)

# Create a matrix
m <- matrix(1:10,nrow=2)

# Create a dataframe
df <- head(mtcars,3)

class(v)
v

class(m)
m

class(df)
df

[1] "numeric"

[1] 1 2 3

[1] "matrix"

[,1] [,2] [,3] [,4] [,5]
[1,] 1    3    5    7     9  
[2,] 2    4    6    8    10

[1] "data.frame"

mpg  cyl disp hp  drat wt    qsec  vs am gear carb
Mazda RX4     21.0 6   160  110 3.90 2.620 16.46 0  1  4    4   
Mazda RX4 Wag 21.0 6   160  110 3.90 2.875 17.02 0  1  4    4   
Datsun 710    22.8 4   108   93 3.85 2.320 18.61 1  1  4    1

# Using List

We we can use list() to combine all these data structures into one list

In [2]:
my.list <- list(v,m,df)
my.list

[[1]]
[1] 1 2 3

[[2]]
     [,1] [,2] [,3] [,4] [,5]
[1,]    1    3    5    7    9
[2,]    2    4    6    8   10

[[3]]
               mpg cyl disp  hp drat    wt  qsec vs am gear carb
Mazda RX4     21.0   6  160 110 3.90 2.620 16.46  0  1    4    4
Mazda RX4 Wag 21.0   6  160 110 3.90 2.875 17.02  0  1    4    4
Datsun 710    22.8   4  108  93 3.85 2.320 18.61  1  1    4    1

Notice that the list() assigns numbers to each object in the list. We can also assign names to each object using the following method

In [3]:
my.named.list <- list(sample.vec =v,sample.matrix = m, sample.df = df)

In [4]:
my.named.list

$sample.vec
[1] 1 2 3

$sample.matrix
     [,1] [,2] [,3] [,4] [,5]
[1,]    1    3    5    7    9
[2,]    2    4    6    8   10

$sample.df
               mpg cyl disp  hp drat    wt  qsec vs am gear carb
Mazda RX4     21.0   6  160 110 3.90 2.620 16.46  0  1    4    4
Mazda RX4 Wag 21.0   6  160 110 3.90 2.875 17.02  0  1    4    4
Datsun 710    22.8   4  108  93 3.85 2.320 18.61  1  1    4    1

## Selecting objects from a list

You can select objects from a list by using the bracket notation. Double brackets grab the object form in the list.

In [5]:
my.named.list[1] # You can pull the object by the index number
my.named.list['sample.vec'] # Or you can pull the values by the name

$sample.vec
[1] 1 2 3

$sample.vec
[1] 1 2 3

In [6]:
class(my.named.list['sample.vec']) # Pulling the vector out of the list still means it's a list!

[1] "list"

In [7]:
class(my.named.list[['sample.vec']]) # You can use double brackets to pull the actual data type

[1] "numeric"

In [8]:
my.named.list$sample.matrix # You can also use the $ to pull values out of the matrix
class(my.named.list$sample.matrix) # This will preserve the data type

[,1] [,2] [,3] [,4] [,5]
[1,] 1    3    5    7     9  
[2,] 2    4    6    8    10

[1] "matrix"

In [9]:
#We can also pull data out of the matrix and df the same way we would normally
my.named.list[['sample.matrix']][,3]
my.named.list$sample.df[1:2,1:4]

[1] 5 6

mpg cyl disp hp 
Mazda RX4     21  6   160  110
Mazda RX4 Wag 21  6   160  110

# Combining Lists
Lists can hold other lists too! We can use the c() function to combine them!

In [10]:
double.list <- c(my.named.list, my.named.list)

In [11]:
double.list

$sample.vec
[1] 1 2 3

$sample.matrix
     [,1] [,2] [,3] [,4] [,5]
[1,]    1    3    5    7    9
[2,]    2    4    6    8   10

$sample.df
               mpg cyl disp  hp drat    wt  qsec vs am gear carb
Mazda RX4     21.0   6  160 110 3.90 2.620 16.46  0  1    4    4
Mazda RX4 Wag 21.0   6  160 110 3.90 2.875 17.02  0  1    4    4
Datsun 710    22.8   4  108  93 3.85 2.320 18.61  1  1    4    1

$sample.vec
[1] 1 2 3

$sample.matrix
     [,1] [,2] [,3] [,4] [,5]
[1,]    1    3    5    7    9
[2,]    2    4    6    8   10

$sample.df
               mpg cyl disp  hp drat    wt  qsec vs am gear carb
Mazda RX4     21.0   6  160 110 3.90 2.620 16.46  0  1    4    4
Mazda RX4 Wag 21.0   6  160 110 3.90 2.875 17.02  0  1    4    4
Datsun 710    22.8   4  108  93 3.85 2.320 18.61  1  1    4    1

In [12]:
str(double.list)

List of 6
 $ sample.vec   : num [1:3] 1 2 3
 $ sample.matrix: int [1:2, 1:5] 1 2 3 4 5 6 7 8 9 10
 $ sample.df    :'data.frame':	3 obs. of  11 variables:
  ..$ mpg : num [1:3] 21 21 22.8
  ..$ cyl : num [1:3] 6 6 4
  ..$ disp: num [1:3] 160 160 108
  ..$ hp  : num [1:3] 110 110 93
  ..$ drat: num [1:3] 3.9 3.9 3.85
  ..$ wt  : num [1:3] 2.62 2.88 2.32
  ..$ qsec: num [1:3] 16.5 17 18.6
  ..$ vs  : num [1:3] 0 0 1
  ..$ am  : num [1:3] 1 1 1
  ..$ gear: num [1:3] 4 4 4
  ..$ carb: num [1:3] 4 4 1
 $ sample.vec   : num [1:3] 1 2 3
 $ sample.matrix: int [1:2, 1:5] 1 2 3 4 5 6 7 8 9 10
 $ sample.df    :'data.frame':	3 obs. of  11 variables:
  ..$ mpg : num [1:3] 21 21 22.8
  ..$ cyl : num [1:3] 6 6 4
  ..$ disp: num [1:3] 160 160 108
  ..$ hp  : num [1:3] 110 110 93
  ..$ drat: num [1:3] 3.9 3.9 3.85
  ..$ wt  : num [1:3] 2.62 2.88 2.32
  ..$ qsec: num [1:3] 16.5 17 18.6
  ..$ vs  : num [1:3] 0 0 1
  ..$ am  : num [1:3] 1 1 1
  ..$ gear: num [1:3] 4 4 4
  ..$ carb: num [1:3] 4 4 1


That's it for lists and that completes our section on basic data structures!